### ISSUE TITLE
Make tests independent from (often changing) data

### ISSUE THREAD

**Issue by Han2-Ro** [YoungVision-eV/website#64]
https://github.com/YoungVision-eV/website/pull/52#issuecomment-1946339365

**Comment by MrGreenTea** [comment]
In general we should think of a testing strategy so we don't depend on things:
- editable/changing data (dates, pictures, events, ...)
- current date

**Comment by MrGreenTea** [comment]
Also very relevant with #38 as we expect our posts to change every few days. I think I'll use the [mask](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1-option-mask) option to hide them for now. But this means we won't be able to verify the images are actually shown :(

**Comment by MrGreenTea** [comment]
See these Vercel environment variables: https://vercel.com/docs/projects/environment-variables/system-environment-variables

Perhaps using `VERCEL_ENV === preview` could work for the github actions.

**Comment by MrGreenTea** [comment]
We'll probably need something like this to test that calendar and other time sensitive data

https://github.com/vesln/timekeeper

**Comment by MrGreenTea** [comment]
Also of interest for playwright: https://github.com/microsoft/playwright/issues/6347#issuecomment-1085850728

**Comment by Han2-Ro** [comment]
- [ ] events
- [ ] instagram posts
- [ ] testamonials

**Comment by MrGreenTea** [comment]
> * [x]  events
> 
>     * [ ]  instagram posts
> 
>     * [ ]  testamonials
> 
> 
> Is that all. We have donations.ts and exercises.ts, but these are not really often changing data, are they?

I think you're right. If we see that we edit those we can change it then.

**Comment by MrGreenTea** [comment]
@Han2-Ro I've had to revert your PR #80 because it caused the main branch to fail. See #89 

We probably shouldn't run the tests against the vercel built version anymore and build the website in Github actions for the tests.

Remove the `PLAYWRIGHT_TEST_BASE_URL` variable and run the workflow `on: [pull_request, merge_queue]`

https://github.com/YoungVision-eV/website/blob/b3e36d2d8a504c80e902c2274322d94028d30087/.github/workflows/playwright.yml#L29

**Comment by MrGreenTea** [comment]
One drawback I've just noticed: We can't test if our links in production are valid anymore :(

Perhaps in the future we should run some basic tests against production deployments as well?

There is also the possibility of replacing the changing elements with [`stylepath`](https://playwright.dev/docs/test-snapshots#stylepath) for example.
